### ISSUE TITLE
某些MOD产生的文件会导致备份失败

### ISSUE THREAD

**Issue by itkzj** [SkyDynamic/QuickBackupM-Fabric#11]
### 运行`/qb make` 报错
`§a备份§r失败，错误原因F:\Games\PrismLauncher\instances\1.20.1(1)\.minecraft\saves\Test\.\datapacks\AmsData`
此文件是Carpet Ams Addition这个MOD产生的(https://modrinth.com/mod/carpet-ams-addition)
### 临时解决办法
禁用Carpet Ams Addition可正常运行`/qb make`

### Steps to reproduce / 复现步骤

1. 安装Carpet Ams Addition及其依赖MOD
2. 创建世界
3. 运行`/qb make`
4. 报错`§a备份§r失败，错误原因F:\Games\PrismLauncher\instances\1.20.1(1)\.minecraft\saves\Test\.\datapacks\AmsData`

### 日志链接
https://api.mclo.gs/1/raw/i1uda41

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.0.2

### MOD列表
advancementinfo-1.20-fabric0.83.0-1.4
alternate-current-mc1.20-1.7.0
amecs-1.3.10+mc.1.20.1
animatica-0.6+1.20
antighost-1.20-fabric0.83.0-1.1.5
appleskin-fabric-mc1.20.1-2.5.1
architectury-9.2.14-fabric
authme-7.0.2+1.20
betterbeds-1.3.0-1.19.3
BetterF3-7.0.2-Fabric-1.20.1
bettermounthud-1.2.2
BetterPingDisplay-Fabric-1.20.1-1.1.1
betterstats-3.9.7+fabric-1.20.1
bobby-5.0.1(1)
borderless-mining-1.1.8+1.20.1
capes-1.5.2+1.20-fabric
Carpet-AMS-Addition-mc1.20.1-fabric-v2.41.0
carpet-extra-1.20-1.4.115
CarpetTCTCAddition-all-2.2.212+46263e3-stable
carpet-tis-addition-mc1.20.1-v1.58.0
chat_heads-0.10.32-fabric-1.20
cherishedworlds-fabric-6.1.6+1.20.1
chunksfadein-v1.0.5-1.20.1
Chunky-1.3.138
citresewn-1.1.5+1.20.1
clientcommands-2.8.5
cloth-config-11.1.118-fabric
continuity-3.0.0-beta.4+1.20.1
custom-crosshair-mod-v1.5.3-fabric-mc1.20.1
CustomSkinLoader_Fabric-14.19.1
Debugify-1.20.1+2.0
durabilityviewer-1.20-fabric0.83.0-1.10.5
dynamic-fps-3.4.3+minecraft-1.20.0-fabric
eating-animation-1.20+1.9.61
enhancedblockentities-0.9+1.20
entity_model_features_fabric_1.20.1-2.0.1(2)
entity_texture_features_fabric_1.20.1-6.0.1(1)
entityculling-fabric-1.6.2-mc1.20.1
fabric-api-0.92.1+1.20.1
fabric-carpet-1.20-1.4.112+v230608
fabric-language-kotlin-1.10.19+kotlin.1.9.23
fabricskyboxes-0.7.3+mc1.20.1
fabrishot-1.10.1
ferritecore-6.0.1-fabric
fsb-interop-1.3.6+mc1.20.1-build.50
gugle-carpet-addition-2.7.0-1.20.1
held-item-info-1.5.0
holdthatchunk-2.0.1+1.19
I18nUpdateMod-3.5.3-all
imblockerfabric-1.0.24
ImmediatelyFast-Fabric-1.2.12+1.20.4
indium-1.0.30+mc1.20.4
iris-1.7.0+mc1.20.1
itemscroller-fabric-1.20.1-0.20.0
itemswapper-fabric-0.6.1-mc1.20.1
Jade-1.20-fabric-11.8.0
krypton-0.2.3
lambdynamiclights-2.3.2+1.20.1
language-reload-1.5.10+1.20.1
lazydfu-0.1.3
LetMeClickAndSend-mc1.20.1-fabric-v1.1.0
litematica-fabric-1.20.1-0.15.3
lithium-fabric-mc1.20.1-0.11.2
logcleaner-1.0.0
magiclib-all-0.7.398+fe2125a-stable
malilib-fabric-1.20.1-0.16.3
MasaGadget-all-3.2.334+08c8f70-stable
mcwifipnp-1.6.9-1.20.1-fabric
memoryleakfix-fabric-1.17+-1.1.5
minihud-fabric-1.20.1-0.27.0
MixinConflictHelper-1.2.0
mixintrace-1.1.1+1.17
modelfix-1.15-fabric
modernfix-fabric-5.17.0+mc1.20.1
modmenu-7.2.2
morechathistory-1.3.0
moreculling-1.20.4-0.24.0
MouseTweaks-fabric-mc1.20-2.26
NoChatReports-FABRIC-1.20.1-v2.2.2
notenoughanimations-fabric-1.7.2-mc1.20.1
oh-my-minecraft-client-1.20.1-0.5.332+477abff-beta
optigui-2.1.7
owo-lib-0.11.2+1.20
PluslsCarpetAddition-1.20.1-0.3.190+9e97daa-beta
PresenceFootsteps-1.9.3
QuickBackupMulti-mc1.20-v2.0.2
reden-is-what-we-made-0.1.2+1.20.1-stable
reeses_sodium_options-1.7.2+mc1.20.1-build.101
RoughlyEnoughItems-12.1.725-fabric
skinlayers3d-fabric-1.6.3-mc1.20.1
sodium-extra-0.5.4+mc1.20.1-build.115
sodium-fabric-0.5.8+mc1.20.1
sound-physics-remastered-fabric-1.20.1-1.3.1
soundsbegone-1.2.5
syncmatica-1.20.1-0.3.11
tcdcommons-3.9.7+fabric-1.20.1
tweakermore-mc1.20.1-v3.17.0
tweakeroo-fabric-1.20.1-0.17.1
TweakMyClient-all-3.6.414+a05e7bf-stable
viafabricplus-2.8.7(1)
waveycapes-fabric-1.4.5-mc1.20.1
wraith-colormeoutlines-1.1.2
xaeroarrowfix-fabric-1.3+1.20
xaero-map-addition-1.20.1-0.2.96+bcdd81f-beta
Xaeros_Minimap_24.1.1_Fabric_1.20
XaerosWorldMap_1.38.4_Fabric_1.20
XaeroZoomout-Fabric-1.20-1.1.0
YetAnotherConfigLib-3.4.1+1.20.1-fabric

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by itkzj** [comment]
禁用Carpet Ams Addition可正常运行`/qb make`
但旧存档已存在Carpet Ams Addition的相关文件，若不删除，仍报错。

**Comment by SkyDynamic** [comment]
草，怎么ams的datapack是个文件夹
收到，晚点看看
