### ISSUE TITLE
[BUG] 输入完备份指令 会卡住将近半分钟

### ISSUE THREAD

**Issue by fgr178707** [SkyDynamic/QuickBackupM-Fabric#12]
### Bug description / Bug描述

输入 /qb make 然后就卡住不动了

[视频补充.zip](https://github.com/SkyDynamic/QuickBackupM-Fabric/files/15217800/default.zip)

github 文件大小限制，只能这样了

### Steps to reproduce / 复现步骤

输入 /qb make 然后就卡住不动了

### Relevant logs / 相关日志

没有报错就卡住了，得好一会儿才能加载出来

### Minecraft version / Minecraft版本

1.20.3

### Mod version / Mod版本

2.0.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
它指令那里会提示你为什么发生错误
反正现在看着你是没开内置数据库, 你可以使用`/qb setting database useInternalDataBase set true`再试试

**Comment by fgr178707** [comment]
> qb make

可以了
