### ISSUE TITLE
使用指令 /qb make 后显示 备份失败，错误原因Is a directory

### ISSUE THREAD

**Issue by kukemc** [SkyDynamic/QuickBackupM-Fabric#14]
### Bug description / Bug描述

使用指令 /qb make 后显示 备份失败，错误原因Is a directory
![image](https://github.com/SkyDynamic/QuickBackupM-Fabric/assets/95417077/02ad7c1b-b69c-4fcb-9db4-ded7da9f7dbe)

### Steps to reproduce / 复现步骤

1. 创建一个世界
2. 进入世界
3. 输入 /qb make 指令

### Expected behavior / 预期行为

备份成功

### Actual behavior / 实际情况

备份失败，错误原因Is a directory

### Relevant logs / 相关日志

后台没有报错
显示：
[02:00:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[02:00:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[02:00:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[02:00:25] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.0.2

### Other information / 其他信息

安装地毯和一些性能优化mod
我看路径 ./QuickBackupMulti 中有备份的文件 但是输入/qb list 显示当前没有任何备份

### Check list

- [x] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
被中断了，没有写入到数据库
你补充一下存档文件夹目录或者直接打包发咱

**Comment by SkyDynamic** [comment]
看了一下，应该是别的mod创建的文件夹导致的，我这里看见的是`Essential Commands`Mod的问题，这些一般不备份，过滤掉。一般是是影响了`世界区块 / 玩家数据`的才会备份，`数据包`等一类的不会进行备份

**Comment by SkyDynamic** [comment]
我现在设置一下过滤器

**Comment by kukemc** [comment]
> 我现在设置一下过滤器

okok 谢谢
