### ISSUE TITLE
/qb make xx  试图执行该命令时出现意外错误

### ISSUE THREAD

**Issue by OMO-404** [SkyDynamic/QuickBackupM-Fabric#17]
### Bug description / Bug描述

试图执行该命令时出现意外错误
![wrong](https://github.com/SkyDynamic/QuickBackupM-Fabric/assets/156062129/2735cd2f-445d-46e5-941a-c98cdb614d2a)

### Steps to reproduce / 复现步骤

1.进入世界
2.执行/qb make
3.等待一会之后，出现 试图执行该命令时出现意外错误

### Expected behavior / 预期行为

备份成功

### Actual behavior / 实际情况

试图执行该命令时出现意外错误

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.0.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
请看#12, 该问题不是mod bug
