### ISSUE TITLE
备份失败，错误原因 null

### ISSUE THREAD

**Issue by Immortal-Sty** [SkyDynamic/QuickBackupM-Fabric#18]
### Bug description / Bug描述

无法备份，看的是 B 站黑山大叔给的[最新的教程](https://www.bilibili.com/video/BV1xM4m1Z7hw/?share_source=copy_web&vd_source=8d7568e730c54d5e89cacd671299bb35)。

### Steps to reproduce / 复现步骤

输入 `/qb make` 后回车。

### Expected behavior / 预期行为

备份成功。

### Actual behavior / 实际情况

显示如下：

```
备份中…请稍等
备份失败，错误原因 null
```

### Relevant logs / 相关日志

- [log](https://pastebin.com/aAqYf3ry)，密码是 `p1MbDhF6dp`；
- 没看到 `crash-reports` 文件夹。

### Minecraft version / Minecraft版本

1.19.4

### Mod version / Mod版本

2.0.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by Immortal-Sty** [comment]
再补充一下，在运行后，服务器无法正常关闭实例了，得强行停止才行，很奇怪。

我用的是 MCSM 管理面板。

**Comment by SkyDynamic** [comment]
怪，这个没法判断问题（因为咱写的这个错误有问题，现在dev版已经加上了`throwable`。可以的话先丢弃所有备份(即为删除`QuickBackupMulti`文件夹)并且更换为action中的dev build版试试

**Comment by Immortal-Sty** [comment]
- [log](https://pastebin.com/1dASG8DT)
- 密码：`NssFwpKAAT`

**Comment by SkyDynamic** [comment]
没看见任何Log Error，能否补充在客户端看见的报错

**Comment by Immortal-Sty** [comment]
哇，有更专业的大佬来了，我也是这个样，新版报错由 null 变成了 nullnull。

**Comment by SkyDynamic** [comment]
> 补充一下
> 更换了[v2.0.5+build.73](https://github.com/SkyDynamic/QuickBackupM-Fabric/actions/runs/9030097026)进行测试
>  
> Java版本：zulu-21.0.1
> Minecraft Server版本：1.19.4
> Fabirc版本：0.15.11
> Fabirc API版本：0.87.2
> 
> 输入qb make xxx 输出如下
> ```
> java.lang.NullPointerException: null
>         at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
>         at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:215) ~[?:?]
>         at java.nio.file.Path.resolve(Path.java:516) ~[?:?]
>         at dev.skydynamic.quickbackupmulti.utils.MakeUtils.make(MakeUtils.java:209) ~[QuickBackupMulti-mc1.19.4-v2.0.5+build.73.jar:?]
>         at dev.skydynamic.quickbackupmulti.command.MakeCommand.makeSaveBackup(MakeCommand.java:28) ~[QuickBackupMulti-mc1.19.4-v2.0.5+build.73.jar:?]
>         at dev.skydynamic.quickbackupmulti.command.MakeCommand.lambda$static$1(MakeCommand.java:20) ~[QuickBackupMulti-mc1.19.4-v2.0.5+build.73.jar:?]
>         at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
>         at net.minecraft.class_2170.method_9249(class_2170.java:285) ~[server-intermediary.jar:?]
>         at net.minecraft.class_2170.method_44252(class_2170.java:278) ~[server-intermediary.jar:?]
>         at net.minecraft.class_3176.method_13941(class_3176.java:299) ~[server-intermediary.jar:?]
>         at net.minecraft.class_3176.method_3813(class_3176.java:284) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.handler$zbf000$carpet$modifiedRunLoop(MinecraftServer.java:6936) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[server-intermediary.jar:?]
>         at java.lang.Thread.run(Thread.java:1583) ~[?:?]
> ```
> [21:52:13] [Server thread/INFO]: §a备份§r失败，错误原因nullnull
> 
> ------
> 
> 备份操作执行后发现，备份文件已被创建但列表中无法查询，也无法进行恢复。
> 

感谢提交，晚点看一下，谢谢

**Comment by SkyDynamic** [comment]
> 回馈：使用[dev2.0.5+build.75](https://github.com/SkyDynamic/QuickBackupM-Fabric/actions/runs/9042013579)
> 无法备份问题已解决
> 
> -----
> 
> 但还原时会出现服务器端崩溃情况
> 
> [crash-log1](https://pastebin.com/fynvzpEK) 密码:zAGAmr1jG6   
> 服务器执行恢复计划时出现
> 
> [crash-log2](https://pastebin.com/DLXJnz1x) 密码:3S3uWcDn7G  
> 恢复后重启时会出现崩溃，第二次恢复正常
> 
> 如果以上两个情况时正常现象的话那就没什么问题了
> 
> 辛苦了

请另外提交issue

**Comment by HereXianggeGe** [comment]
使用[dev2.0.5+build.75](https://github.com/SkyDynamic/QuickBackupM-Fabric/actions/runs/9042013579)
没有弹出  开始备份
服务端弹出命令 No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: no further information}}]}. Waiting for 30000 ms before timing out
玩家会自动掉线
使用版本：1.20.1 加装地毯端 未加其他mods
