### ISSUE TITLE
使用 /qb make 

### ISSUE THREAD

**Issue by Manticore333** [SkyDynamic/QuickBackupM-Fabric#20]
### Bug description / Bug描述

![image](https://github.com/SkyDynamic/QuickBackupM-Fabric/assets/102736548/ee8472ca-1923-4a3e-b2d0-2475ab01e5f4)

### Steps to reproduce / 复现步骤

在已經玩一陣子的存檔中新增這個模組，使用/qb make  ，然後就遇到了

### Actual behavior / 实际情况

無法備份，但會在QuickBackupMultiy的檔案夾中，新增一個跟備份名字相同的空檔案夾

### Minecraft version / Minecraft版本

1.19.4

### Mod version / Mod版本

v2.0.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
#11
