### ISSUE TITLE
进入存档出现崩溃问题

### ISSUE THREAD

**Issue by STSwordfish** [SkyDynamic/QuickBackupM-Fabric#21]
### Bug description / Bug描述

游戏崩溃，提示为quickbackup导致崩溃，但也可能是跟某模组冲突
![2024-05-15_14 56 05](https://github.com/SkyDynamic/QuickBackupM-Fabric/assets/169889767/da90074c-0cfd-4cf2-90c5-e970066fe902)

### Steps to reproduce / 复现步骤

1，启动游戏（HMCL）
2，进入一个单人存档

### Expected behavior / 预期行为

成功进入单人存档游玩

### Actual behavior / 实际情况

游戏崩溃，即使是装了not enough crashes模组,在进入存档提示崩溃后标题屏幕，出现无法退出游戏的问题（点退出游戏没反应，任务栏强制关闭也不行）。另外一个问题是有的存档可以正常进去，有的就要崩溃，而且一旦出现崩溃，其他存档也进不去了，并提示相同的内容。

### Relevant logs / 相关日志

[crash-2024-05-15_14.59.48-server.txt](https://github.com/SkyDynamic/QuickBackupM-Fabric/files/15319192/crash-2024-05-15_14.59.48-server.txt)

### Minecraft version / Minecraft版本

1.20.4

### Mod version / Mod版本

2.0.2

### Other information / 其他信息

1，装了地毯及其较多的附属（扩展,tis,org,gca,pca,tctc,ams）
2，装了MASA全家桶
3，一些优化模组

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
请暂时使用action内的dev build版本（最新为build.77）
