### ISSUE TITLE
备份失败

### ISSUE THREAD

**Issue by DoubtedYapper71** [SkyDynamic/QuickBackupM-Fabric#22]
### Bug description / Bug描述

备份报错Cannot invoke
![image](https://github.com/SkyDynamic/QuickBackupM-Fabric/assets/107922760/f451d303-4ae6-4ce3-aea4-b2a9e7c04e5a)

### Steps to reproduce / 复现步骤

自动备份或手动备份

### Expected behavior / 预期行为

正常备份

### Actual behavior / 实际情况

备份失败

### Relevant logs / 相关日志

[latest.log](https://github.com/SkyDynamic/QuickBackupM-Fabric/files/15321024/latest.log)

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.0.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
请您先使用dev版本尝试一下？还是不行的话再发一次log和截图把，谢谢支持

**Comment by DoubtedYapper71** [comment]
release中没有dev版本？
