### ISSUE TITLE
关闭实例后mcsmanager中无法判定为关闭状态

### ISSUE THREAD

**Issue by Rushbe2021** [SkyDynamic/QuickBackupM-Fabric#24]
### Bug description / Bug描述

在运行于mcsmanager的服务器实例关闭后一直显示状态为停止中（实际上好像已经关闭成功了，这是mcsmanager无法检测已关闭，最后一行代码是“ThreadedAnvilChunkStorage: All dimensions are saved”）

### Steps to reproduce / 复现步骤

条件：
1、运行在mcsmanager面板服中的实例
2、添加了此mod

### Minecraft version / Minecraft版本

1.20.1

### Mod version / Mod版本

2.0.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
怀疑数据库线程没杀干净
